@BaseUrl=http://127.0.0.1:8000


###

POST {{BaseUrl}}/api/v1/policy HTTP/1.1
Content-Type: application/json

{
    "resource_name": "syncbyte-db",
    "resource_type": "database",
    "resource_options": {
        "db_type": "postgresql",
        "version": "14.5",
        "server": "127.0.0.1",
        "port": 5432,
        "user": "syncbyte",
        "password": "123456",
        "db_name": "syncbyte"
    },
    "retention": 7,
    "is_compress": true,
    "schedule_type": "cron",
    "schedule_options": {
        "cron": "* * * * *"
    }
}

###

POST {{BaseUrl}}/api/v1/host HTTP/1.1
Content-Type: application/json

{
    "hostname": "LOCALHOST",
    "ip": "127.0.0.1",
    "host_type": "backup"
}

###

POST {{BaseUrl}}/api/v1/storageunit HTTP/1.1
Content-Type: application/json

{
    "name": "stutest",
    "stu_type": "local",
    "options": {
        "endpoint": "",
        "accesskey":"",
        "secretkey":"",
        "bucket":"",
        "mountpoint":"/tmp"
    }
}

###

POST {{BaseUrl}}/api/v1/backup/job HTTP/1.1
Content-Type: application/json

{
    "policy_id": 1
}

###
