// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: internal/proto/syncbyte.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackupParams    *BackupParams    `protobuf:"bytes,1,opt,name=BackupParams,proto3" json:"BackupParams,omitempty"`
	DataStoreParams *DataStoreParams `protobuf:"bytes,2,opt,name=DataStoreParams,proto3" json:"DataStoreParams,omitempty"`
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_syncbyte_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_syncbyte_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_syncbyte_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRequest) GetBackupParams() *BackupParams {
	if x != nil {
		return x.BackupParams
	}
	return nil
}

func (x *BackupRequest) GetDataStoreParams() *DataStoreParams {
	if x != nil {
		return x.DataStoreParams
	}
	return nil
}

type BackupParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourcePath string `protobuf:"bytes,1,opt,name=SourcePath,proto3" json:"SourcePath,omitempty"`
}

func (x *BackupParams) Reset() {
	*x = BackupParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_syncbyte_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupParams) ProtoMessage() {}

func (x *BackupParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_syncbyte_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupParams.ProtoReflect.Descriptor instead.
func (*BackupParams) Descriptor() ([]byte, []int) {
	return file_internal_proto_syncbyte_proto_rawDescGZIP(), []int{1}
}

func (x *BackupParams) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

type DataStoreParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MountPoint string `protobuf:"bytes,1,opt,name=MountPoint,proto3" json:"MountPoint,omitempty"`
}

func (x *DataStoreParams) Reset() {
	*x = DataStoreParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_syncbyte_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataStoreParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataStoreParams) ProtoMessage() {}

func (x *DataStoreParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_syncbyte_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataStoreParams.ProtoReflect.Descriptor instead.
func (*DataStoreParams) Descriptor() ([]byte, []int) {
	return file_internal_proto_syncbyte_proto_rawDescGZIP(), []int{2}
}

func (x *DataStoreParams) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

type BackupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Path      string      `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size      int64       `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	MD5       string      `protobuf:"bytes,4,opt,name=MD5,proto3" json:"MD5,omitempty"`
	PartInfos []*PartInfo `protobuf:"bytes,5,rep,name=PartInfos,proto3" json:"PartInfos,omitempty"`
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_syncbyte_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_syncbyte_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_syncbyte_proto_rawDescGZIP(), []int{3}
}

func (x *BackupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BackupResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BackupResponse) GetMD5() string {
	if x != nil {
		return x.MD5
	}
	return ""
}

func (x *BackupResponse) GetPartInfos() []*PartInfo {
	if x != nil {
		return x.PartInfos
	}
	return nil
}

type PartInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32  `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	MD5   string `protobuf:"bytes,2,opt,name=MD5,proto3" json:"MD5,omitempty"`
	Size  int64  `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *PartInfo) Reset() {
	*x = PartInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_syncbyte_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartInfo) ProtoMessage() {}

func (x *PartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_syncbyte_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartInfo.ProtoReflect.Descriptor instead.
func (*PartInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_syncbyte_proto_rawDescGZIP(), []int{4}
}

func (x *PartInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PartInfo) GetMD5() string {
	if x != nil {
		return x.MD5
	}
	return ""
}

func (x *PartInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_internal_proto_syncbyte_proto protoreflect.FileDescriptor

var file_internal_proto_syncbyte_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x79, 0x6e, 0x63, 0x62, 0x79, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x0d, 0x42, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0c, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x52, 0x0c, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x12, 0x40, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x52, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x22, 0x2e, 0x0a, 0x0c, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x22, 0x31, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4d, 0x6f, 0x75, 0x6e,
	0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x0e, 0x42, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x44, 0x35, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4d, 0x44, 0x35, 0x12, 0x2d, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x50, 0x61, 0x72,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x46, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x44, 0x35, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x44, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x32, 0x45,
	0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x62, 0x79, 0x74, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6b, 0x79, 0x6c, 0x69, 0x6e, 0x65, 0x39, 0x33, 0x2f, 0x73, 0x79,
	0x6e, 0x63, 0x62, 0x79, 0x74, 0x65, 0x2d, 0x67, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_syncbyte_proto_rawDescOnce sync.Once
	file_internal_proto_syncbyte_proto_rawDescData = file_internal_proto_syncbyte_proto_rawDesc
)

func file_internal_proto_syncbyte_proto_rawDescGZIP() []byte {
	file_internal_proto_syncbyte_proto_rawDescOnce.Do(func() {
		file_internal_proto_syncbyte_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_syncbyte_proto_rawDescData)
	})
	return file_internal_proto_syncbyte_proto_rawDescData
}

var file_internal_proto_syncbyte_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_syncbyte_proto_goTypes = []interface{}{
	(*BackupRequest)(nil),   // 0: proto.BackupRequest
	(*BackupParams)(nil),    // 1: proto.BackupParams
	(*DataStoreParams)(nil), // 2: proto.DataStoreParams
	(*BackupResponse)(nil),  // 3: proto.BackupResponse
	(*PartInfo)(nil),        // 4: proto.PartInfo
}
var file_internal_proto_syncbyte_proto_depIdxs = []int32{
	1, // 0: proto.BackupRequest.BackupParams:type_name -> proto.BackupParams
	2, // 1: proto.BackupRequest.DataStoreParams:type_name -> proto.DataStoreParams
	4, // 2: proto.BackupResponse.PartInfos:type_name -> proto.PartInfo
	0, // 3: proto.Syncbyte.Backup:input_type -> proto.BackupRequest
	3, // 4: proto.Syncbyte.Backup:output_type -> proto.BackupResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_syncbyte_proto_init() }
func file_internal_proto_syncbyte_proto_init() {
	if File_internal_proto_syncbyte_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_syncbyte_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_syncbyte_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_syncbyte_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataStoreParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_syncbyte_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_syncbyte_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_syncbyte_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_syncbyte_proto_goTypes,
		DependencyIndexes: file_internal_proto_syncbyte_proto_depIdxs,
		MessageInfos:      file_internal_proto_syncbyte_proto_msgTypes,
	}.Build()
	File_internal_proto_syncbyte_proto = out.File
	file_internal_proto_syncbyte_proto_rawDesc = nil
	file_internal_proto_syncbyte_proto_goTypes = nil
	file_internal_proto_syncbyte_proto_depIdxs = nil
}
