// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: internal/proto/syncbyte.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SyncbyteServiceClient is the client API for SyncbyteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncbyteServiceClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type syncbyteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncbyteServiceClient(cc grpc.ClientConnInterface) SyncbyteServiceClient {
	return &syncbyteServiceClient{cc}
}

func (c *syncbyteServiceClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SyncbyteService/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncbyteServiceServer is the server API for SyncbyteService service.
// All implementations must embed UnimplementedSyncbyteServiceServer
// for forward compatibility
type SyncbyteServiceServer interface {
	Call(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSyncbyteServiceServer()
}

// UnimplementedSyncbyteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSyncbyteServiceServer struct {
}

func (UnimplementedSyncbyteServiceServer) Call(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedSyncbyteServiceServer) mustEmbedUnimplementedSyncbyteServiceServer() {}

// UnsafeSyncbyteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncbyteServiceServer will
// result in compilation errors.
type UnsafeSyncbyteServiceServer interface {
	mustEmbedUnimplementedSyncbyteServiceServer()
}

func RegisterSyncbyteServiceServer(s grpc.ServiceRegistrar, srv SyncbyteServiceServer) {
	s.RegisterService(&SyncbyteService_ServiceDesc, srv)
}

func _SyncbyteService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncbyteServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SyncbyteService/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncbyteServiceServer).Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncbyteService_ServiceDesc is the grpc.ServiceDesc for SyncbyteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncbyteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SyncbyteService",
	HandlerType: (*SyncbyteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _SyncbyteService_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/syncbyte.proto",
}
